// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Hotsapi.Uploader.Mac
{
	public partial class SettingsController : NSViewController
	{
		public SettingsController (IntPtr handle) : base (handle)
		{
		}
	}
}
